- src/app/action-item/action-item.component.ts
- src/app/action-list/action-list.component.css
- src/app/action-list/action-list.component.ts
- src/app/app.component.ts
- src/app/app.constants.ts
- src/app/app.module.ts
- src/app/build/build.component.css
- src/app/build/build.component.ts
- src/app/config-screen/config-screen.component.ts
- src/app/config.service.ts
- src/app/pull-request/pull-request.component.ts
- src/app/refresh.service.ts
- src/config/app-config-constants.ts
- src/domain/action-item.ts
- src/github/services/github.service.ts
- src/github/services/vsts.service.ts
- src/jenkins/services/jenkins.service.ts
> add vsts builds

- README.md
> update vsts perms in doc

- src/github/services/vsts-repos.ts
> Add new library repos

- src/github/services/vsts-repos.ts
@blackbaud/micro-cervezas - is this the only change to get our team's work on the MFAB?
cc @blackbaud/highlander
> add highlander team for vsts

- src/github/services/vsts-repos.ts
> adding common-logging for micro

- src/github/services/vsts-repos.ts
> adding identity-token to micro

- .angular-cli.json
- package.json
- src/index.html
the office wifi has a tendency to hang on the third-party calls every now
and then. mainly affects dev, but i've see affect the board as well.
> compile third-party css w/ angular

- src/github/services/vsts-repos.ts
add common-provider-pact to wab action board
> LUM-24499.add-pact-lib

- src/github/services/vsts-repos.ts
- src/jenkins/services/jenkins.service.ts
>  allow for empty watch list

- src/github/services/vsts-repos.ts
> adding actions-adapter to WAB! repos

- src/jenkins/services/jenkins.service.ts
> Quick fix to get develop builds on action board

- README.md
> Add git token scope details to README

- src/github/services/vsts-repos.ts
and just remove it from batman. we got it from a build-perspective
> correct comma issue

- src/github/services/vsts-repos.ts
@blackbaud/micro-cervezas - would like to add some highlander vsts repos please
> Adding more highlander vsts repos

- src/github/services/vsts-repos.ts
> adding constituent adapter repo to WAB!

- src/github/services/vsts-repos.ts
@blackbaud/micro-cervezas Hi, we have VSTS repos now. Is this all we need to do to get our team on the board?
> Adding Voltron to VSTS MF Action Board

- src/github/services/vsts-repos.ts
@blackbaud/micro-cervezas  - ready for review
> adding another highlander vsts repo

- src/github/services/vsts-repos.ts
> add scs-definition-lng-lonextgen to micro

- src/github/services/vsts-repos.ts
> add common-retry to micro

- src/github/services/vsts-repos.ts
> add wfd dev docs to WBA!

- src/github/services/vsts-repos.ts
> adding our sharable component library

- src/github/services/vsts.service.ts
sometimes there are many definitions that match the original search, so, let's find the exact definition
> search for release ids

- src/github/services/vsts-repos.ts
> add form lib, common-ui-test lib

- package.json
- src/app/action-item/action-item.component.spec.ts
- src/domain/action-item.ts
I feel terrible that I can't actually test this other than in production.  I blame @Blackbaud-ColbyWhite...
> Vsts do not merge tag

- src/github/services/vsts-repos.ts
@blackbaud/micro-cervezas I am looking for feedback on patterns to implement reducers and actions. Demo is in skyux-spa-reactive-demo.
> [ADD_REACTIVE_DEMO_SPA] Adding skyux-spa-reactive-demo to micro's board

- src/github/services/vsts-repos.ts
> add transactor to highlander mf action board

- src/github/services/vsts-repos.ts
> add don-form-int-tests for highlander

- src/app/action-item/action-item.component.spec.ts
- src/domain/action-item.ts
> Consume vsts DO NOT MERGE label

- src/github/services/vsts-repos.ts
> remove donation forms spa from highlander

- src/github/services/vsts-repos.ts
> Add donor form to micro

- src/github/services/vsts-repos.ts
@blackbaud/micro-cervezas - Please review. Thanks!
> Add Cerebro team repos for VSTS

- src/github/services/vsts-repos.ts
> add missing comma

- src/github/services/vsts-repos.ts
> added new vsts repo to highlander list

- src/github/services/vsts-repos.ts
> corrected repo name

- README.md
- scripts/deploy.js
once there are some changes to deploy, i'll test this branch, but wanted to get it pushed off my computer until then
> remove credentials from deploy script and use profile

- src/github/services/vsts-repos.ts
Add skyux-lib-browser-cache to the list of repos for We Are Batman!
@blackbaud/we-are-batman 
> Add browser-cache library to WAB

- src/github/services/vsts-repos.ts
@blackbaud/micro-cervezas @blackbaud/brady-bunch Adding in our newest repo for Brady Bunch.
> add social-posting-int-tests

- src/github/services/vsts-repos.ts
@blackbaud/voltron 
Update Voltron vsts repos
> LUM-29242 Update Voltron vsts repos

- src/app/action-list/action-list.component.ts
> properly set the scope

- src/app/action-list/action-list.component.ts
> really properly set the scope

- src/github/services/vsts-repos.ts
This repo doesn't exist anymore ... i'm not sure why ...
> removing scs-definition-lng-lonextgen

- src/app/sprint-lit/sprint-lit.component.html
Updates sprint lit image to our new intern champion
> Update lit image

- src/github/services/vsts-repos.ts
For team formerly known as Brady Bunch
cc @blackbaud/brady-bunch
> Add social smoke tests repo

- src/github/services/vsts-repos.ts
@blackbaud/micro-cervezas  - ready for review
> remove skyux-lib-form from highlander mf action board

- src/github/services/vsts-repos.ts
> added donation-form-layout for highlander

- src/app/action-list/action-list.component.html
- src/app/build/build.component.html
- src/domain/action-item.ts
> expose build type and show a truck for releases

- src/app/action-item/action-item.component.spec.ts
- src/domain/action-item.ts
- src/github/services/vsts.service.ts
> implement preDeployApprovals for VSTS releases

- src/github/services/vsts-repos.ts
adding new client library to mfab for voltron
> LUM-25832 add new library

- scripts/deploy.js
we'll eventually want to fix this properly with #165
> make sure to deploy the lit folder

- scripts/deploy.js
> print file name when deploying

- scripts/deploy.js
> handle err when deploying

- package.json
> fixing help script name

- src/github/services/vsts-repos.ts
Add `social-metrics` to Animaniacs MFAB.
@blackbaud/micro-cervezas @blackbaud/brady-bunch (PS remind me to update this alias)
> add social-metrics

- src/github/services/vsts-repos.ts
@blackbaud/micro-cervezas please review and merge
> Update Animaniacs team repos (and sort)

- src/github/services/vsts-repos.ts
> add missing comma from #172

- src/github/services/vsts-repos.ts
Adding skyux-spa-workflows-supportal to our list of repos
Ordering repos by type (non-skyux or skyux (library or spa)) and alphabetically by name
> Add new repo for WAB team & order repos by type and name

- src/github/services/vsts-repos.ts
> LUM-30426 add synth monitor to micro action board

- src/github/services/vsts-repos.ts
> add repos to highlanders list

- src/github/services/vsts-repos.ts
Adding our prod tester repo to the WAB board
> Add Prod Tester repo to WAB board

- src/github/services/vsts-repos.ts
> add supportal repo to highlanders list

- src/github/services/vsts-repos.ts
updating common-payments-client to java-client-payments to reflect the name change
> LUM-31927 update client library name

- src/app/action-item/action-item.component.spec.ts
- src/domain/action-item.ts
> mark draft PRs as do not merge

- src/github/services/vsts-repos.ts
> add admin console SPA to action board

- src/github/services/vsts-repos.ts
> LUM-32952 Remove common-async and sasquatch from highlander board

- src/github/services/vsts-repos.ts
> Update Animaniacs team name and repos

- src/github/services/vsts-repos.ts
> added new repo

- src/github/services/vsts-repos.ts
> adding new dlq lib to WAB!

- src/github/services/vsts-repos.ts
> add email adapter to WAB

- src/github/services/vsts-repos.ts
> Remove common repos from Micro

- README.md
I had to enable SSO on my token to get it to work.  Updating the README to mention enabling SSO
> Update readme to mentiona enabling SSO on your github token

- src/github/services/vsts-repos.ts
> add email-adapter to Highlanders board

- src/github/services/vsts-repos.ts
> LUM-34490: add new environment-form-config to highlander

- src/app/action-list/action-list.component.spec.ts
- src/app/action-list/action-list.component.ts
- src/app/app.component.spec.ts
- src/app/app.module.ts
- src/app/build/build.component.spec.ts
- src/app/config-screen/config-screen.component.spec.ts
- src/app/config.service.ts
- src/app/pull-request/pull-request.component.spec.ts
- src/app/rage-face/rage-face.component.spec.ts
- src/app/shared/services/jenkins.service.spec.ts
- src/app/shared/services/jenkins.service.ts
- src/app/sprint-lit/sprint-lit.component.spec.ts
- src/config/app-config-constants.ts
- src/jenkins/services/jenkins.service.ts
- src/testing/constants.ts
looks like we don't have any infrastructure set up to test this - can someone give me a hand tomorrow to figure out how to test this super private method change?
> show LO builds if subscribed to luminate-online repo

- src/github/services/vsts-repos.ts
> Add synth tests

- src/github/services/vsts-repos.ts
> Add tools settings spa to highlander

- src/github/services/vsts-repos.ts
> added efcfg release to the highlander page

- README.md
- scripts/deploy.js
> update docs and profile to use new tool for AWS authentication

- src/github/services/vsts-repos.ts
> Remove micro projects

- src/github/services/vsts-repos.ts
> add consent and transactor AKS releases

- src/github/services/vsts-repos.ts
> add illuminati team

- src/github/services/vsts-repos.ts
> Add donation forms SPA to highlander action board

- src/github/services/vsts-repos.ts
- src/github/services/vsts.service.ts
> aks services and fixing bug

- src/github/services/vsts-repos.ts
> add facebook-api-client to illuminati

- src/github/services/vsts-repos.ts
@blackbaud/micro-cervezas - We don't need receipter anymore, could you please approve this PR?
> Removing receipter from Cerebro's list

- src/github/services/vsts-repos.ts
> Edit micro projects

- src/github/services/vsts-repos.ts
@blackbaud/micro-cervezas please review and merge
> Add relationship service for Animaniacs

- src/github/services/vsts-repos.ts
> [ATT-3874] Adding Relationship Form SkyUX Library

- PULL_REQUEST_TEMPLATE.md
> Remove PR template since any team can merge

- src/github/services/vsts-repos.ts
> Add micro repos

- src/app/app.constants.ts
> Bumping polling time

- src/github/services/vsts-repos.ts
> Remove unused / deprecated Animaniacs repos
